CREATE TYPE "ItemType" AS ENUM ('PRODUCT', 'SERVICE');
CREATE TYPE "StockMovementType" AS ENUM ('RECEIPT', 'ISSUE', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT');
CREATE TYPE "AdjustmentStatus" AS ENUM ('DRAFT', 'APPROVED', 'VOID');
CREATE TYPE "ProjectStatus" AS ENUM ('PLANNED', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED');
CREATE TABLE "Product" ("id" UUID NOT NULL, "organizationId" UUID NOT NULL, "sku" TEXT NOT NULL, "name" TEXT NOT NULL, "type" "ItemType" NOT NULL DEFAULT 'PRODUCT', "category" TEXT, "description" TEXT, "unit" TEXT NOT NULL DEFAULT 'unit', "salePrice" DECIMAL(19,4) NOT NULL DEFAULT 0, "costPrice" DECIMAL(19,4) NOT NULL DEFAULT 0, "taxRate" DECIMAL(7,4) NOT NULL DEFAULT 0, "reorderLevel" DECIMAL(19,4) NOT NULL DEFAULT 0, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Product_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Warehouse" ("id" UUID NOT NULL, "organizationId" UUID NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "address" TEXT, "manager" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Warehouse_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StockMovement" ("id" UUID NOT NULL, "organizationId" UUID NOT NULL, "productId" UUID NOT NULL, "warehouseId" UUID NOT NULL, "type" "StockMovementType" NOT NULL, "quantity" DECIMAL(19,4) NOT NULL, "unitCost" DECIMAL(19,4) NOT NULL DEFAULT 0, "movementDate" DATE NOT NULL, "reference" TEXT NOT NULL, "transferGroupId" UUID, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "StockMovement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StockAdjustment" ("id" UUID NOT NULL, "organizationId" UUID NOT NULL, "productId" UUID NOT NULL, "warehouseId" UUID NOT NULL, "reference" TEXT NOT NULL, "adjustmentDate" DATE NOT NULL, "quantityDelta" DECIMAL(19,4) NOT NULL, "unitCost" DECIMAL(19,4) NOT NULL DEFAULT 0, "reason" TEXT NOT NULL, "status" "AdjustmentStatus" NOT NULL DEFAULT 'DRAFT', "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "StockAdjustment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Project" ("id" UUID NOT NULL, "organizationId" UUID NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "client" TEXT, "owner" TEXT NOT NULL, "startDate" DATE NOT NULL, "endDate" DATE, "budget" DECIMAL(19,4) NOT NULL DEFAULT 0, "actualCost" DECIMAL(19,4) NOT NULL DEFAULT 0, "revenue" DECIMAL(19,4) NOT NULL DEFAULT 0, "status" "ProjectStatus" NOT NULL DEFAULT 'PLANNED', "description" TEXT, "tasks" JSONB NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Project_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Product_organizationId_sku_key" ON "Product"("organizationId", "sku");
CREATE INDEX "Product_organizationId_type_isActive_idx" ON "Product"("organizationId", "type", "isActive");
CREATE UNIQUE INDEX "Warehouse_organizationId_code_key" ON "Warehouse"("organizationId", "code");
CREATE INDEX "Warehouse_organizationId_isActive_idx" ON "Warehouse"("organizationId", "isActive");
CREATE UNIQUE INDEX "StockMovement_organizationId_reference_key" ON "StockMovement"("organizationId", "reference");
CREATE INDEX "StockMovement_organizationId_movementDate_idx" ON "StockMovement"("organizationId", "movementDate");
CREATE INDEX "StockMovement_productId_warehouseId_idx" ON "StockMovement"("productId", "warehouseId");
CREATE INDEX "StockMovement_transferGroupId_idx" ON "StockMovement"("transferGroupId");
CREATE UNIQUE INDEX "StockAdjustment_organizationId_reference_key" ON "StockAdjustment"("organizationId", "reference");
CREATE INDEX "StockAdjustment_organizationId_status_adjustmentDate_idx" ON "StockAdjustment"("organizationId", "status", "adjustmentDate");
CREATE UNIQUE INDEX "Project_organizationId_code_key" ON "Project"("organizationId", "code");
CREATE INDEX "Project_organizationId_status_idx" ON "Project"("organizationId", "status");
ALTER TABLE "Product" ADD CONSTRAINT "Product_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Warehouse" ADD CONSTRAINT "Warehouse_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockAdjustment" ADD CONSTRAINT "StockAdjustment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockAdjustment" ADD CONSTRAINT "StockAdjustment_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockAdjustment" ADD CONSTRAINT "StockAdjustment_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
